---
# This playbook deploys prestashop app.  
- hosts: "{{ stackname }}-db"
  remote_user: centos
  become: yes
  #become_method: sudo

  vars:
    - stackname: "psstack"
    - consulip: "10.10.0.5"
    - consulport: "8500"
#    - restddb: true
#    - forcepublicurl: "10.3.222.89:60080"
  
  roles:
    - v4/db

- hosts: "{{ stackname }}-asg*"
  become: yes
  #become_method: sudo

  vars:
    - stackname: "psstack"
    - consulip: "10.10.0.5"
    - consulport: "8500"
  
  roles:
    - v4/web

- hosts: "{{ stackname }}-ha"
  become: yes
  #become_method: sudo

  vars:
    - stackname: "psstack"
    - consulip: "10.10.0.5"
    - consulport: "8500"
  
  roles:
    - v4/haproxy
