---
# This playbook deploys prestashop app.  
- hosts: "{{ stackname }}-db"
  remote_user: centos
  become: yes
  #become_method: sudo

  vars:
    - stackname: "psstack"
    - consulip: "10.10.0.5"
    - consulport: "8500"
    - publicurl: "ansible.clouddemo.hpintelco.org:60080"
  
  roles:
    - v3/db

- hosts: "{{ stackname }}-web"
  become: yes
  #become_method: sudo

  vars:
    - stackname: "psstack"
    - consulip: "10.10.0.5"
    - consulport: "8500"
  
  roles:
    - v3/web
